services:
  - type: web
    name: ehspro-api
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: mysql,render
      - key: DB_HOST
        value: mysql-ehs-kbnalpha-bbce.l.aivencloud.com
      - key: DB_PORT
        value: "15129"
      - key: DB_NAME
        value: ehs_db
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: API_USERNAME
        value: ehs-api
      - key: API_PASSWORD
        generateValue: true
      - key: SMTP_HOST
        value: smtp-relay.brevo.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        value: bbd299001@smtp-brevo.com
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM
        value: kbnalpha@gmail.com
      - key: SMTP_AUTH
        value: "true"
      - key: SMTP_STARTTLS
        value: "true"
