spring:
  application:
    name: ehspro-api
  profiles:
    default: mysql
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  sql:
    init:
      mode: never
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  jackson:
    deserialization:
      fail-on-unknown-properties: true
server:
  error:
    include-message: never
