package com.ehspro.dto;
import java.time.*;
import java.util.*;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.databind.JsonNode;
import com.ehspro.model.*;
public class EmployeeDto extends BaseDto {
    @com.fasterxml.jackson.annotation.JsonProperty(access=com.fasterxml.jackson.annotation.JsonProperty.Access.READ_ONLY) public Long systemAccountId;
    @com.fasterxml.jackson.annotation.JsonProperty(access=com.fasterxml.jackson.annotation.JsonProperty.Access.READ_ONLY) public Long basicRoleId;
    @com.fasterxml.jackson.annotation.JsonProperty(access=com.fasterxml.jackson.annotation.JsonProperty.Access.READ_ONLY) public Set<Long> additionalRoleIds;
    @com.fasterxml.jackson.annotation.JsonProperty(access=com.fasterxml.jackson.annotation.JsonProperty.Access.READ_ONLY) public String systemUsername;
    @com.fasterxml.jackson.annotation.JsonProperty(access=com.fasterxml.jackson.annotation.JsonProperty.Access.READ_ONLY) public Boolean systemAccountEnabled;
    @Size(max=20) public String countryCode;
    @NotBlank @Size(max = 2000) public String firstName;
    @Size(max = 2000) public String middleName;
    @NotBlank @Size(max = 2000) public String lastName;
    @Size(max = 2000) public String emailAddress;
    @Size(max = 2000) public String phoneNumber;
    public Long profilePictureId;
    @NotNull @Min(1) public Integer gender;
    public Long department;
    public LocalDate dateOfJoining;
    public Long contractorId;
    public Integer accessFailedCount;
    @NotNull public Long designation;
    public Integer userType;
    @NotNull @Min(1) @Max(2) public Integer status;
    @NotBlank @Size(max = 100) public String userNumber;
    public Long tenantID;
    @NotNull public Long languageID;
    @NotNull public Long organizationUnitId;
    public Boolean hasAccess = false;
    public Boolean isMobileUser = false;
    @Size(max = 2000) public String alias;
    @PastOrPresent public LocalDate dateOfBirth;
    public Integer age;
    public Long country;
    public Boolean isSubscribed = false;
    @Valid public List<@NotNull Long> userRoleIds = new ArrayList<>();
    @Valid public List<@NotNull Long> organizationUnitIds = new ArrayList<>();
    @Valid public List<@NotNull Long> organizationUnitIdsMapped = new ArrayList<>();
    @Valid public List<@NotNull Long> organizationUnitListIds = new ArrayList<>();
    public JsonNode uploadedFiles;
    @Size(max = 2000) public String password;
    @Size(max = 2000) public String departmentName;
    @Size(max = 2000) public String designationName;
    @Size(max = 2000) public String contractorName;
    @Size(max = 2000) public String organizationUnitNames;
    @Size(max = 2000) public String workerTypeName;
    @Size(max = 2000) public String userRoleNames;
    @Size(max = 2000) public String genderText;
    @Size(max = 2000) public String contractorNameText;
    @Size(max = 2000) public String fullName;
    @Size(max = 2000) public String organizationUnitName;
    @Size(max = 2000) public String countryName;
    @Size(max = 2000) public String profilePictureUrl;
}
